# Configuration for using acid

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 256
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
bootloader = {}
bootstrap = {}
acid = {}
coreutils = {}
# TODO: Does this need escalated?
escalated = {}
initfs = {}
ion = {}
ipcd = {}
kernel = {}
ptyd = {}

# User settings
[users.root]
password = "password"
uid = 0
gid = 0
name = "root"
home = "/root"

[users.user]
# Password is unset
password = ""

[[files]]
path = "/etc/init.d/00_base"
data = """
ipcd
ptyd
escalated
"""

[[files]]
path = "/etc/init.d/10_acid"
data = """
export RUST_BACKTRACE full
acid
acid create_test
acid switch
acid tls
acid thread
shutdown
"""

[[files]]
path = "/usr/bin"
data = "../bin"
symlink = true

[[files]]
path = "/usr/games"
data = "../games"
symlink = true

[[files]]
path = "/usr/include"
data = "../include"
symlink = true

[[files]]
path = "/usr/lib"
data = "../lib"
symlink = true

[[files]]
path = "/usr/share"
data = "../share"
symlink = true

[[files]]
path = "/tmp"
data = ""
directory= true
# 0o1777
mode = 1023
